language: cpp

compiler: gcc

install:
  - sudo apt-add-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5
  - sudo apt-get update
  - sudo apt-get install qtdeclarative5-dev qt5-qmake

script:
  - qmake Platform-Game.pro
  - make 	
